name: Maven Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Docker daemon service for TestContainers
      docker:
        image: docker:dind
        options: --privileged
        ports:
          - 2375:2375

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Setup proper authentication for GitHub Packages
      - name: Setup Maven settings for GitHub Packages
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const settingsXml = `
            <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                         http://maven.apache.org/xsd/settings-1.0.0.xsd">
              <servers>
                <server>
                  <id>github</id>
                  <username>${process.env.GITHUB_ACTOR}</username>
                  <password>${process.env.PACKAGES_TOKEN}</password>
                </server>
              </servers>
            </settings>
            `;
            fs.mkdirSync('~/.m2', { recursive: true });
            fs.writeFileSync('~/.m2/settings.xml', settingsXml);

      - name: Set up JDK 21 for project
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'

      - name: Install Chrome driver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d. -f1)
          echo "Chrome version: $CHROME_VERSION"
          # WebDriverManager will handle chromedriver installation in your tests

      # Configure TestContainers to use Docker daemon
      - name: Configure TestContainers
        run: |
          echo "testcontainers.reuse.enable=true" > ~/.testcontainers.properties

      # Create directory for test recordings/screenshots
      - name: Create test directories
        run: |
          mkdir -p test-recordings
          mkdir -p test-results

      - name: Build with Maven (skipping tests)
        run: mvn -B package --file pom.xml -DskipTests -Pproduction
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      - name: Run tests with UI tests in headless mode
        run: |
          mvn test -Dtest=ProductListViewTest -Dselenium.headless=true -Pproduction
        env:
          # Set environment variables for headless testing
          SELENIUM_HEADLESS: "true"
          # Ensure Vaadin runs in production mode to avoid dev server issues
          VAADIN_PRODUCTION_MODE: "true"
          # Make test containers accessible from GitHub runner
          DOCKER_HOST: "tcp://localhost:2375"
          # Any ports needed for your tests
          SERVER_PORT: 8080
          # Java options for memory, etc.
          MAVEN_OPTS: "-Xmx2048m"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
        continue-on-error: true  # Continue workflow even if tests fail to collect reports

      # Generate Maven site with test reports
      - name: Generate Site Reports
        run: mvn site -DgenerateReports=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
        continue-on-error: true

      # Generate test summary report
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()  # Always run this step to publish test results even if tests fail
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
          summary: true
          fail_on_failure: false

      # Upload test recordings and screenshots as artifacts
      - name: Upload test artifacts and reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            test-recordings/
            test-results/
            target/surefire-reports/
            target/failsafe-reports/
            target/site/
          retention-days: 7
